name: Python CI
on:
    workflow_run:
        workflows: ["Check & Create PR"]
        types:
            - completed
    push:
        branches:
            - dev
            - homolog
            - prod
jobs:
  testApp:
      environment:
          name: ${{ github.ref }}
      runs-on: ubuntu-latest
      permissions:
          id-token: write
          contents: read
      steps:
        - name: Setting stage, stack name
          run: |
            echo "STAGE=${{ secrets.STAGE }}" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: Installing Dependencies
          run: |
            pip install -r requirements-dev.txt
        - name: Setup envs
          run: |
            echo STAGE=${{ secrets.STAGE }} >> $GITHUB_ENV
        - name: Run Tests
          run: |
            pytest --ignore=iac
          env:
              STAGE: ${{ secrets.STAGE }}